"""empty message

Revision ID: 71e52dedec68
Revises: dd645ea59b7a
Create Date: 2023-11-13 00:04:10.624212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e52dedec68'
down_revision: Union[str, None] = 'dd645ea59b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_users_purchasers',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.drop_table('books_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_users',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='books_users_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='books_users_user_id_fkey')
    )
    op.drop_table('books_users_purchasers')
    # ### end Alembic commands ###
