"""empty message

Revision ID: dd645ea59b7a
Revises: 1840a6a81014
Create Date: 2023-11-12 23:10:00.538823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd645ea59b7a'
down_revision: Union[str, None] = '1840a6a81014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_users', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('books_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('books_users_books_id_fkey', 'books_users', type_='foreignkey')
    op.drop_constraint('books_users_users_id_fkey', 'books_users', type_='foreignkey')
    op.create_foreign_key(None, 'books_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'books_users', 'books', ['book_id'], ['id'])
    op.drop_column('books_users', 'books_id')
    op.drop_column('books_users', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_users', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books_users', sa.Column('books_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books_users', type_='foreignkey')
    op.drop_constraint(None, 'books_users', type_='foreignkey')
    op.create_foreign_key('books_users_users_id_fkey', 'books_users', 'users', ['users_id'], ['id'])
    op.create_foreign_key('books_users_books_id_fkey', 'books_users', 'books', ['books_id'], ['id'])
    op.drop_column('books_users', 'user_id')
    op.drop_column('books_users', 'book_id')
    # ### end Alembic commands ###
